### PR TITLE
Make compression pluggable and bridge default to gzip

### PR DESCRIPTION
**Pull request by danehammer**

### CODE REVIEW

**Comment by danehammer** [comment]
Note to myself: didn't need to use JUnit 3 style, other author did so unnecessarily, storm already depends on junit 4.

**Comment by danehammer** [comment]
I've tested this in a mini-test cluster (to be fair, on my 0.8.2 fork) in each permutation. Checked with zkCli.sh that the size of serializations was much smaller with gzip so I knew it was using the various delegates (for a small topology we have, the assignments node is 16kb with default, and 2kb with gzip).

**Comment by revans2** [comment]
I like your code a lot better than what I put together, especially the bridge code.  My only comment would be around the junit 3 vs 4 styles.  I'll run through the tests and if everything looks good I'll merge it in and update the unit test style.

**Comment by revans2** [comment]
@danehammer 

Shoot, I didn't see this before the new files don't have an apache header in them.  I assume that because you did a pull request to me on an Apache licensed project that your code is licensed under an apache 2 license and it will be OK for me to add the header into the files.  Please let me know if that is not correct.

**Comment by danehammer** [comment]
No, I just forgot. Go ahead and add the headers.

**Pull request merged**
